import {
  Dumbbell,
  BookOpen,
  Footprints,
  Gamepad2,
  Smartphone,
  Tv,
  Play,
  ShoppingBag,
  Droplets,
  Moon,
  Sun,
  Heart,
  Brain,
  Coffee,
  Apple,
  Bike,
  Music,
  Pencil,
  Code,
  Wallet,
  Leaf,
  Flame,
  Target,
  Sparkles,
  Layers,
  Bed,
  Salad,
  Timer,
  Sunrise,
  Waves,
  MessageCircle,
  Cookie,
  Plane,
  Smile,
  Palette,
  Guitar,
  ShoppingCart,
  Ban,
  Brush,
  Flower2,
  GraduationCap,
  Ticket,
  MessageSquare,
  DollarSign,
  Briefcase,
  House,
  Utensils,
  Mountain,
  LayoutGrid,
  Cross,
  type LucideIcon,
} from "lucide-react";

/** Icons a user can pick for a habit or category. Stored as the string key, so this is data-driven. */
export const HABIT_ICONS: Record<string, LucideIcon> = {
  target: Target,
  "book-open": BookOpen,
  dumbbell: Dumbbell,
  footprints: Footprints,
  bike: Bike,
  waves: Waves,
  "gamepad-2": Gamepad2,
  smartphone: Smartphone,
  tv: Tv,
  play: Play,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  wallet: Wallet,
  droplets: Droplets,
  apple: Apple,
  salad: Salad,
  cookie: Cookie,
  coffee: Coffee,
  moon: Moon,
  sun: Sun,
  sunrise: Sunrise,
  bed: Bed,
  heart: Heart,
  brain: Brain,
  smile: Smile,
  leaf: Leaf,
  flame: Flame,
  sparkles: Sparkles,
  timer: Timer,
  pencil: Pencil,
  code: Code,
  music: Music,
  guitar: Guitar,
  palette: Palette,
  "message-circle": MessageCircle,
  plane: Plane,
  ban: Ban,
  layers: Layers,
  brush: Brush,
  "flower-2": Flower2,
  "graduation-cap": GraduationCap,
  ticket: Ticket,
  "message-square": MessageSquare,
  "dollar-sign": DollarSign,
  briefcase: Briefcase,
  house: House,
  utensils: Utensils,
  mountain: Mountain,
  "layout-grid": LayoutGrid,
  cross: Cross,
};

export const HABIT_ICON_KEYS = Object.keys(HABIT_ICONS);

export function habitIcon(key: string): LucideIcon {
  return HABIT_ICONS[key] ?? Target;
}
